#ifndef NUMERICAL_DISPLAY_SHARED_H
#define NUMERICAL_DISPLAY_SHARED_H

#ifdef NUMERICAL_DISPLAY_STATIC
#   define NUMERICAL_DISPLAY_EXPORT
#else
#  if defined(NUMERICAL_DISPLAY_LIBRARY)
#    define NUMERICAL_DISPLAY_EXPORT Q_DECL_EXPORT
#  else
#    define NUMERICAL_DISPLAY_EXPORT Q_DECL_IMPORT
#  endif
#endif
#endif // NUMERICAL_DISPLAY_SHARED_H
