#ifndef GAUGE_HORIZONTAL_SHARED_H
#define GAUGE_HORIZONTAL_SHARED_H

#if defined(GAUGE_HORIZONTAL_LIBRARY)
#  define GAUGE_HORIZONTAL_EXPORT Q_DECL_EXPORT
#else
#  define GAUGE_HORIZONTAL_EXPORT Q_DECL_IMPORT
#endif

#endif // GAUGE_HORIZONTAL_SHARED_H
