#ifndef STATE_DISPLAY_SHARED_H
#define STATE_DISPLAY_SHARED_H

#if defined(STATE_DISPLAY_LIBRARY)
#  define STATE_DISPLAY_EXPORT Q_DECL_EXPORT
#else
#  define STATE_DISPLAY_EXPORT Q_DECL_IMPORT
#endif

#endif // STATE_DISPLAY_SHARED_H
